### ISSUE TITLE
Working Example For NodeJS or HTML?

### ISSUE THREAD

**Issue by PRFinklemeister** [LightningK0ala/satoshis.place#2]
NodeJS Output From Sample  Code...

(function (exports, require, module, __filename, __dirname) { import io from 'socket.io-client'
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

**Comment by jcsmesquita** [comment]
Use one of the latest versions of Nodejs with ES6 support. Alternatively rewrite with `var ... = require(...)`

**Comment by LightningK0ala** [comment]
You need to be on a version of Node.js that supports ES6.

**Comment by LightningK0ala** [comment]
Example updated to not require ES6 import.
